/* =============================================================================
 * AI 发展史知识图谱数据 —— 完整版 (300+ 节点)
 * 在「核心版 134」(window.AI_DATA) 基础上扩展，新增约 187 个节点与对应边。
 * 节点/边 schema 与 data.js 完全一致；id 统一加年份后缀避免重名。
 * 每条 edge 的 source/target 必须对应真实存在的 node id。
 * ===========================================================================*/
(function () {
  "use strict";
  const BASE = window.AI_DATA; // 核心版 134 节点集合（由 data.js 先加载）

  const NEW_NODES = [
    /* ============================ 人物 Person ============================ */
    { id: "mcculloch_1943", label: "Warren McCulloch", type: "Person", year: 1943, paradigm: "connectionism", era: "奠基", image: "👤", url: "https://en.wikipedia.org/wiki/Warren_McCulloch", description: "神经网络的数学奠基者之一，1943 年与 Pitts 提出 MP 神经元模型。" },
    { id: "pitts_1943", label: "Walter Pitts", type: "Person", year: 1943, paradigm: "connectionism", era: "奠基", image: "👤", url: "https://en.wikipedia.org/wiki/Walter_Pitts", description: "逻辑神经元模型合作者，MP 模型共同提出者。" },
    { id: "hebb_1949", label: "Donald Hebb", type: "Person", year: 1949, paradigm: "connectionism", era: "奠基", image: "👤", url: "https://en.wikipedia.org/wiki/Donald_Hebb", description: "提出『赫布学习律』：同时激活的神经元连接增强。" },
    { id: "widrow_1960", label: "Bernard Widrow", type: "Person", year: 1960, paradigm: "connectionism", era: "奠基", image: "👤", url: "https://en.wikipedia.org/wiki/Bernard_Widrow", description: "1960 年提出 ADALINE 自适应线性神经元。" },
    { id: "werbos_1944", label: "Paul Werbos", type: "Person", year: 1944, paradigm: "connectionism", era: "联结主义", image: "👤", url: "https://en.wikipedia.org/wiki/Paul_Werbos", description: "1974 年博士论文提出反向传播思想，早于 1986 年重提。" },
    { id: "fukushima_1980", label: "福岛邦彦 (Kunihiko Fukushima)", type: "Person", year: 1980, paradigm: "connectionism", era: "联结主义", image: "👤", url: "https://en.wikipedia.org/wiki/Kunihiko_Fukushima", description: "1980 年提出 Neocognitron，卷积神经网络的雏形。" },
    { id: "sejnowski_1947", label: "Terrence Sejnowski", type: "Person", year: 1947, paradigm: "connectionism", era: "联结主义", image: "👤", url: "https://en.wikipedia.org/wiki/Terrence_Sejnowski", description: "玻尔兹曼机共同提出者，计算神经科学大家。" },
    { id: "sutton_1958", label: "Richard Sutton", type: "Person", year: 1958, paradigm: "symbolism", era: "强化学习", image: "👤", url: "https://en.wikipedia.org/wiki/Richard_S._Sutton", description: "强化学习奠基人，时序差分与 Actor-Critic 方法。" },
    { id: "barto_1948", label: "Andrew Barto", type: "Person", year: 1948, paradigm: "symbolism", era: "强化学习", image: "👤", url: "https://en.wikipedia.org/wiki/Andrew_Barto", description: "强化学习先驱，与 Sutton 合著经典教材。" },
    { id: "watkins_1958", label: "Chris Watkins", type: "Person", year: 1958, paradigm: "symbolism", era: "强化学习", image: "👤", url: "https://en.wikipedia.org/wiki/Christopher_Watkins", description: "1989 年提出 Q-Learning。" },
    { id: "pearl_1936", label: "Judea Pearl", type: "Person", year: 1936, paradigm: "symbolism", era: "统计学习", image: "👤", url: "https://en.wikipedia.org/wiki/Judea_Pearl", description: "贝叶斯网络与因果推断之父，2011 年图灵奖。" },
    { id: "zadeh_1965", label: "Lotfi Zadeh", type: "Person", year: 1965, paradigm: "symbolism", era: "统计学习", image: "👤", url: "https://en.wikipedia.org/wiki/Lotfi_A._Zadeh", description: "1965 年提出模糊逻辑。" },
    { id: "kurzweil_1948", label: "Ray Kurzweil", type: "Person", year: 1948, paradigm: "scaling", era: "大模型", image: "👤", url: "https://en.wikipedia.org/wiki/Ray_Kurzweil", description: "未来学家，奇点理论倡导者，现任职 Google。" },
    { id: "brooks_1954", label: "Rodney Brooks", type: "Person", year: 1954, paradigm: "connectionism", era: "强化学习", image: "👤", url: "https://en.wikipedia.org/wiki/Rodney_Brooks", description: "行为主义机器人学，iRobot 与 Rethink Robotics 创始人。" },
    { id: "thrun_1967", label: "Sebastian Thrun", type: "Person", year: 1967, paradigm: "connectionism", era: "大数据", image: "👤", url: "https://en.wikipedia.org/wiki/Sebastian_Thrun", description: "自动驾驶与 Udacity 推动者，前 Google X 负责人。" },
    { id: "ng_1976", label: "Andrew Ng (吴恩达)", type: "Person", year: 1976, paradigm: "connectionism", era: "深度学习", image: "👤", url: "https://en.wikipedia.org/wiki/Andrew_Ng", description: "机器学习布道者，Google Brain、Coursera 与百度前 AI 负责人。" },
    { id: "karpathy_1986", label: "Andrej Karpathy", type: "Person", year: 1986, paradigm: "scaling", era: "大模型", image: "👤", url: "https://en.wikipedia.org/wiki/Andrej_Karpathy", description: "前 Tesla AI 负责人，LLM 与可视化教学知名。" },
    { id: "shazeer_1976", label: "Noam Shazeer", type: "Person", year: 1976, paradigm: "scaling", era: "大模型", image: "👤", url: "https://en.wikipedia.org/wiki/Noam_Shazeer", description: "Transformer 共同作者，Character.AI 创始人。" },
    { id: "devlin_1979", label: "Jacob Devlin", type: "Person", year: 1979, paradigm: "scaling", era: "大模型", image: "👤", url: "https://en.wikipedia.org/wiki/Jacob_Devlin", description: "BERT 主要作者。" },
    { id: "radford_1986", label: "Alec Radford", type: "Person", year: 1986, paradigm: "scaling", era: "大模型", image: "👤", url: "https://en.wikipedia.org/wiki/Alec_Radford", description: "GPT 系列与 CLIP 的核心作者。" },
    { id: "leike_1986", label: "Jan Leike", type: "Person", year: 1986, paradigm: "scaling", era: "大模型", image: "👤", url: "https://en.wikipedia.org/wiki/Jan_Leike", description: "RLHF 与对齐研究负责人，曾领导 OpenAI 超级对齐团队。" },
    { id: "russell_1962", label: "Stuart Russell", type: "Person", year: 1962, paradigm: "symbolism", era: "大模型", image: "👤", url: "https://en.wikipedia.org/wiki/Stuart_J._Russell", description: "《人工智能：现代方法》作者，AI 安全倡导者。" },
    { id: "norvig_1956", label: "Peter Norvig", type: "Person", year: 1956, paradigm: "symbolism", era: "大模型", image: "👤", url: "https://en.wikipedia.org/wiki/Peter_Norvig", description: "前 Google 研究总监，AIMA 教材合著者。" },
    { id: "marcus_1969", label: "Gary Marcus", type: "Person", year: 1969, paradigm: "symbolism", era: "大模型", image: "👤", url: "https://en.wikipedia.org/wiki/Gary_Marcus", description: "深度学习质疑者，主张结合符号与神经方法。" },
    { id: "crawford_1971", label: "Kate Crawford", type: "Person", year: 1971, paradigm: "scaling", era: "大模型", image: "👤", url: "https://en.wikipedia.org/wiki/Kate_Crawford", description: "AI 伦理与算法偏见研究学者。" },
    { id: "gebru_1983", label: "Timnit Gebru", type: "Person", year: 1983, paradigm: "scaling", era: "大模型", image: "👤", url: "https://en.wikipedia.org/wiki/Timnit_Gebru", description: "算法偏见研究者，因 AI 伦理争议离开 Google。" },
    { id: "buolamwini_1989", label: "Joy Buolamwini", type: "Person", year: 1989, paradigm: "scaling", era: "大模型", image: "👤", url: "https://en.wikipedia.org/wiki/Joy_Buolamwini", description: " algorithmic bias 研究者，『性别阴影』项目发起人。" },
    { id: "lee_kaifu_1956", label: "李开复 (Kai-Fu Lee)", type: "Person", year: 1956, paradigm: "scaling", era: "大模型", image: "👤", url: "https://en.wikipedia.org/wiki/Kai-Fu_Lee", description: "创新工场创始人，前 Google 中国/微软高管，著《AI 超级大国》。" },
    { id: "shum_1966", label: "沈向洋 (Harry Shum)", type: "Person", year: 1966, paradigm: "scaling", era: "大模型", image: "👤", url: "https://en.wikipedia.org/wiki/Harry_Shum", description: "前微软全球执行副总裁，微软亚洲研究院领导者。" },
    { id: "yang_qiang_1969", label: "杨强 (Qiang Yang)", type: "Person", year: 1969, paradigm: "scaling", era: "大模型", image: "👤", url: "https://en.wikipedia.org/wiki/Qiang_Yang", description: "迁移学习与联邦学习专家，香港科技大学教授。" },
    { id: "zhou_zhihua_1973", label: "周志华", type: "Person", year: 1973, paradigm: "connectionism", era: "深度学习", image: "👤", url: "https://en.wikipedia.org/wiki/Zhi-Hua_Zhou", description: "南京大学机器学习研究所所长，著有《机器学习》(西瓜书)。" },
    { id: "zhang_yaqin_1963", label: "张亚勤 (Ya-Qin Zhang)", type: "Person", year: 1963, paradigm: "scaling", era: "大模型", image: "👤", url: "https://en.wikipedia.org/wiki/Ya-Qin_Zhang", description: "前百度总裁、微软亚洲研究院创始人之一。" },
    { id: "abbeel_1980", label: "Pieter Abbeel", type: "Person", year: 1980, paradigm: "connectionism", era: "强化学习", image: "👤", url: "https://en.wikipedia.org/wiki/Pieter_Abbeel", description: "机器人强化学习专家，Covariant 创始人。" },
    { id: "levine_1983", label: "Sergey Levine", type: "Person", year: 1983, paradigm: "connectionism", era: "强化学习", image: "👤", url: "https://en.wikipedia.org/wiki/Sergey_Levine", description: "机器人深度强化学习研究者。" },
    { id: "finn_1987", label: "Chelsea Finn", type: "Person", year: 1987, paradigm: "connectionism", era: "强化学习", image: "👤", url: "https://en.wikipedia.org/wiki/Chelsea_Finn", description: "元学习与机器人灵巧操作研究。" },
    { id: "jordan_1956", label: "Michael Jordan", type: "Person", year: 1956, paradigm: "symbolism", era: "统计学习", image: "👤", url: "https://en.wikipedia.org/wiki/Michael_I._Jordan", description: "统计机器学习权威，贝叶斯与图模型大家。" },
    { id: "mitchell_1951", label: "Tom Mitchell", type: "Person", year: 1951, paradigm: "symbolism", era: "统计学习", image: "👤", url: "https://en.wikipedia.org/wiki/Tom_M._Mitchell", description: "CMU 机器学习教授，定义『学习』的著名表述。" },
    { id: "domingos_1965", label: "Pedro Domingos", type: "Person", year: 1965, paradigm: "symbolism", era: "统计学习", image: "👤", url: "https://en.wikipedia.org/wiki/Pedro_Domingos", description: "《终极算法》作者，机器学习研究者。" },
    { id: "girshick_1982", label: "Ross Girshick", type: "Person", year: 1982, paradigm: "connectionism", era: "深度学习", image: "👤", url: "https://en.wikipedia.org/wiki/Ross_Girshick", description: "R-CNN 系列目标检测作者。" },
    { id: "fan_jim_1990", label: "Jim Fan (范麟熙)", type: "Person", year: 1990, paradigm: "scaling", era: "大模型", image: "👤", url: "https://x.com/DrJimFan", description: "NVIDIA 高级研究科学家，具身智能与『基础模型』倡导者。" },

    /* ========================== 组织 Organization ========================== */
    { id: "baidu_2000", label: "百度 (Baidu)", type: "Organization", year: 2000, era: "大模型", image: "🏢", url: "https://en.wikipedia.org/wiki/Baidu", description: "中国搜索与 AI 巨头，文心一言与 Apollo 自动驾驶。" },
    { id: "tencent_ai_2016", label: "腾讯 AI Lab", type: "Organization", year: 2016, era: "大模型", image: "🏢", url: "https://ai.tencent.com/", description: "腾讯人工智能实验室，混元大模型与多模态。" },
    { id: "alibaba_damo_2017", label: "阿里达摩院", type: "Organization", year: 2017, era: "大模型", image: "🏢", url: "https://damo.alibaba.com/", description: "阿里巴巴达摩院，通义千问出品方。" },
    { id: "huawei_1987", label: "华为 (Huawei)", type: "Organization", year: 1987, era: "大模型", image: "🏢", url: "https://www.huawei.com/", description: "昇腾算力与盘古大模型，全栈 AI 布局。" },
    { id: "bytedance_2012", label: "字节跳动 (ByteDance)", type: "Organization", year: 2012, era: "大模型", image: "🏢", url: "https://www.bytedance.com/", description: "抖音母公司，豆包等生成式 AI 产品。" },
    { id: "sense_time_2014", label: "商汤科技 (SenseTime)", type: "Organization", year: 2014, era: "大模型", image: "🏢", url: "https://www.sensetime.com/", description: "计算机视觉与元宇宙/大模型公司。" },
    { id: "megvii_2011", label: "旷视科技 (Megvii)", type: "Organization", year: 2011, era: "深度学习", image: "🏢", url: "https://www.megvii.com/", description: "Face++ 与图像识别起家的 AI 公司。" },
    { id: "iflytek_1999", label: "科大讯飞 (iFlytek)", type: "Organization", year: 1999, era: "大模型", image: "🏢", url: "https://www.iflytek.com/", description: "中文语音识别与合成龙头，星火大模型。" },
    { id: "zhipu_2019", label: "智谱 AI (Zhipu)", type: "Organization", year: 2019, era: "大模型", image: "🏢", url: "https://www.zhipuai.cn/", description: "清华系大模型公司，GLM / ChatGLM 系列。" },
    { id: "moonshot_2023", label: "月之暗面 (Moonshot)", type: "Organization", year: 2023, era: "大模型", image: "🏢", url: "https://www.moonshot.cn/", description: "Kimi 长上下文大模型公司。" },
    { id: "minimax_2021", label: "MiniMax", type: "Organization", year: 2021, era: "大模型", image: "🏢", url: "https://www.minimax.io/", description: "中国大模型独角兽，对话与多模态模型。" },
    { id: "zero_one_2023", label: "零一万物 (01.AI)", type: "Organization", year: 2023, era: "大模型", image: "🏢", url: "https://www.01.ai/", description: "李开复创立的开源大模型公司。" },
    { id: "baai_2018", label: "北京智源研究院 (BAAI)", type: "Organization", year: 2018, era: "大模型", image: "🏢", url: "https://www.baai.ac.cn/", description: "悟道大模型与 FlagOpen 开源社区。" },
    { id: "xai_2023", label: "xAI", type: "Organization", year: 2023, era: "大模型", image: "🏢", url: "https://x.ai/", description: "Elon Musk 创立的 AI 公司，Grok 模型。" },
    { id: "stability_2020", label: "Stability AI", type: "Organization", year: 2020, era: "大模型", image: "🏢", url: "https://stability.ai/", description: "开源扩散模型 Stable Diffusion 背后公司。" },
    { id: "huggingface_2016", label: "Hugging Face", type: "Organization", year: 2016, era: "大模型", image: "🏢", url: "https://huggingface.co/", description: "Transformer 模型开源社区与模型库。" },
    { id: "midjourney_2022", label: "Midjourney", type: "Organization", year: 2022, era: "大模型", image: "🏢", url: "https://www.midjourney.com/", description: "高质量文生图模型公司。" },
    { id: "cerebras_2016", label: "Cerebras", type: "Organization", year: 2016, era: "大模型", image: "🏢", url: "https://www.cerebras.net/", description: "晶圆级 (wafer-scale) 超大 AI 芯片公司。" },
    { id: "graphcore_2016", label: "Graphcore", type: "Organization", year: 2016, era: "深度学习", image: "🏢", url: "https://www.graphcore.ai/", description: "英国 AI 芯片公司，IPU 智能处理器。" },

    /* ============================ 概念 Concept ============================ */
    { id: "bayesian_net", label: "贝叶斯网络", type: "Concept", year: 1985, era: "统计学习", image: "💡", url: "https://en.wikipedia.org/wiki/Bayesian_network", description: "用概率图表示变量依赖关系的模型。" },
    { id: "fuzzy_logic", label: "模糊逻辑", type: "Concept", year: 1965, era: "统计学习", image: "💡", url: "https://en.wikipedia.org/wiki/Fuzzy_logic", description: "处理不精确与连续隶属度的逻辑系统。" },
    { id: "causal_inference", label: "因果推断", type: "Concept", year: 1990, era: "统计学习", image: "💡", url: "https://en.wikipedia.org/wiki/Causal_inference", description: "从观测数据中推断因果关系的方向。" },
    { id: "hebbian_learning", label: "赫布学习律", type: "Concept", year: 1949, era: "奠基", image: "💡", url: "https://en.wikipedia.org/wiki/Hebbian_theory", description: "『一起放电的神经元，连在一起』的可塑性法则。" },
    { id: "transfer_learning", label: "迁移学习", type: "Concept", year: 1995, era: "统计学习", image: "💡", url: "https://en.wikipedia.org/wiki/Transfer_learning", description: "将已学知识迁移到新任务。" },
    { id: "few_shot", label: "少样本学习", type: "Concept", year: 2019, era: "大模型", image: "💡", url: "https://en.wikipedia.org/wiki/Few-shot_learning", description: "仅用极少样本即可学习任务。" },
    { id: "self_supervised", label: "自监督学习", type: "Concept", year: 2018, era: "深度学习", image: "💡", url: "https://en.wikipedia.org/wiki/Self-supervised_learning", description: "从无标注数据构造监督信号。" },
    { id: "multimodal", label: "多模态学习", type: "Concept", year: 2018, era: "大模型", image: "💡", url: "https://en.wikipedia.org/wiki/Multimodal_learning", description: "联合处理文本/图像/音频等多种模态。" },
    { id: "moe", label: "混合专家 (MoE)", type: "Concept", year: 2017, era: "大模型", image: "💡", url: "https://en.wikipedia.org/wiki/Mixture_of_experts", description: "以稀疏路由激活部分专家子网络。" },
    { id: "rlhf", label: "人类反馈强化学习 (RLHF)", type: "Concept", year: 2022, era: "大模型", image: "💡", url: "https://en.wikipedia.org/wiki/Reinforcement_learning_from_human_feedback", description: "用人类偏好微调语言模型使其对齐。" },
    { id: "cot", label: "思维链 (CoT)", type: "Concept", year: 2022, era: "大模型", image: "💡", url: "https://en.wikipedia.org/wiki/Chain-of-thought_prompting", description: "让模型分步推理以提升复杂任务表现。" },
    { id: "emergent", label: "涌现能力", type: "Concept", year: 2022, era: "大模型", image: "💡", url: "https://en.wikipedia.org/wiki/Emergence", description: "模型规模足够大后突然具备的新能力。" },
    { id: "world_model", label: "世界模型", type: "Concept", year: 2018, era: "强化学习", image: "💡", url: "https://en.wikipedia.org/wiki/World_model", description: "智能体内部对环境的预测模型。" },
    { id: "embodied_ai", label: "具身智能", type: "Concept", year: 2021, era: "大模型", image: "💡", url: "https://en.wikipedia.org/wiki/Embodied_cognition", description: "在物理/虚拟身体中感知-行动闭环的智能。" },
    { id: "foundation_model", label: "基础模型", type: "Concept", year: 2021, era: "大模型", image: "💡", url: "https://en.wikipedia.org/wiki/Foundation_model", description: "大规模预训练、可适配多种下游任务的模型。" },
    { id: "knowledge_graph", label: "知识图谱", type: "Concept", year: 2012, era: "大数据", image: "💡", url: "https://en.wikipedia.org/wiki/Knowledge_graph", description: "以图结构表示实体与关系。" },
    { id: "machine_translation", label: "机器翻译", type: "Concept", year: 1954, era: "大模型", image: "💡", url: "https://en.wikipedia.org/wiki/Machine_translation", description: "自动将一种语言翻译为另一种。" },
    { id: "object_detection", label: "目标检测", type: "Concept", year: 2001, era: "大数据", image: "💡", url: "https://en.wikipedia.org/wiki/Object_detection", description: "在图像中定位并识别物体。" },
    { id: "image_generation", label: "图像生成", type: "Concept", year: 2014, era: "大模型", image: "💡", url: "https://en.wikipedia.org/wiki/Image_generation", description: "从文本或噪声生成图像。" },
    { id: "tts", label: "语音合成 (TTS)", type: "Concept", year: 1980, era: "大数据", image: "💡", url: "https://en.wikipedia.org/wiki/Speech_synthesis", description: "将文本转换为自然语音。" },
    { id: "qa", label: "问答系统", type: "Concept", year: 1961, era: "大模型", image: "💡", url: "https://en.wikipedia.org/wiki/Question_answering", description: "自动回答自然语言问题。" },
    { id: "recommendation", label: "推荐系统", type: "Concept", year: 1990, era: "大数据", image: "💡", url: "https://en.wikipedia.org/wiki/Recommender_system", description: "根据用户偏好推荐内容或商品。" },
    { id: "graph_learning", label: "图学习", type: "Concept", year: 2009, era: "深度学习", image: "💡", url: "https://en.wikipedia.org/wiki/Graph_neural_network", description: "在图结构数据上学习的范式。" },
    { id: "neural_arch_search", label: "神经架构搜索 (NAS)", type: "Concept", year: 2017, era: "深度学习", image: "💡", url: "https://en.wikipedia.org/wiki/Neural_architecture_search", description: "自动搜索最优网络结构。" },
    { id: "edge_ai", label: "边缘 AI", type: "Concept", year: 2018, era: "大模型", image: "💡", url: "https://en.wikipedia.org/wiki/Edge_computing", description: "在端侧设备本地运行 AI 推理。" },

    /* ========================= 架构 Architecture ========================= */
    { id: "adaline_1960", label: "ADALINE", type: "Architecture", year: 1960, era: "奠基", image: "🏗️", url: "https://en.wikipedia.org/wiki/ADALINE", description: "自适应线性神经元，Widrow-Hoff 规则。" },
    { id: "neocognitron_1980", label: "Neocognitron", type: "Architecture", year: 1980, era: "联结主义", image: "🏗️", url: "https://en.wikipedia.org/wiki/Neocognitron", description: "多层卷积式网络，CNN 的直接先驱。" },
    { id: "autoencoder_1986", label: "自编码器", type: "Architecture", year: 1986, era: "联结主义", image: "🏗️", url: "https://en.wikipedia.org/wiki/Autoencoder", description: "学习数据低维表示的网络。" },
    { id: "rbm_2006", label: "受限玻尔兹曼机 (RBM)", type: "Architecture", year: 2006, era: "深度学习", image: "🏗️", url: "https://en.wikipedia.org/wiki/Restricted_Boltzmann_machine", description: "深度信念网基本单元，Hinton 力推。" },
    { id: "vae_2013", label: "变分自编码器 (VAE)", type: "Architecture", year: 2013, era: "深度学习", image: "🏗️", url: "https://en.wikipedia.org/wiki/Variational_autoencoder", description: "生成式模型，学习潜变量分布。" },
    { id: "unet_2015", label: "U-Net", type: "Architecture", year: 2015, era: "深度学习", image: "🏗️", url: "https://en.wikipedia.org/wiki/U-Net", description: "编码器-解码器结构，医学分割与扩散模型核心。" },
    { id: "yolo_2015", label: "YOLO", type: "Architecture", year: 2015, era: "深度学习", image: "🏗️", url: "https://en.wikipedia.org/wiki/You_Only_Look_Once", description: "单阶段实时目标检测架构。" },
    { id: "googlenet_2014", label: "GoogLeNet / Inception", type: "Architecture", year: 2014, era: "深度学习", image: "🏗️", url: "https://en.wikipedia.org/wiki/Inception_(deep_learning_architecture)", description: "多尺度 Inception 模块，2014 ILSVRC 冠军。" },
    { id: "mobilenet_2016", label: "MobileNet", type: "Architecture", year: 2016, era: "深度学习", image: "🏗️", url: "https://en.wikipedia.org/wiki/MobileNet", description: "轻量深度可分离卷积，面向移动端。" },
    { id: "gnn_2009", label: "图神经网络 (GNN)", type: "Architecture", year: 2009, era: "深度学习", image: "🏗️", url: "https://en.wikipedia.org/wiki/Graph_neural_network", description: "在图结构数据上传播与聚合信息。" },
    { id: "capsule_2017", label: "胶囊网络 (Capsule)", type: "Architecture", year: 2017, era: "深度学习", image: "🏗️", url: "https://en.wikipedia.org/wiki/Capsule_neural_network", description: "Hinton 提出，编码姿态等实体属性。" },
    { id: "vit_2020", label: "Vision Transformer (ViT)", type: "Architecture", year: 2020, era: "大模型", image: "🏗️", url: "https://en.wikipedia.org/wiki/Vision_transformer", description: "将 Transformer 用于图像分类。" },
    { id: "clip_2021", label: "CLIP", type: "Architecture", year: 2021, era: "大模型", image: "🏗️", url: "https://en.wikipedia.org/wiki/CLIP_(model)", description: "图文对比预训练，统一多模态表征。" },
    { id: "dalle_2021", label: "DALL·E", type: "Architecture", year: 2021, era: "大模型", image: "🏗️", url: "https://en.wikipedia.org/wiki/DALL-E", description: "OpenAI 文生图模型，基于 CLIP 潜空间。" },
    { id: "whisper_2022", label: "Whisper", type: "Architecture", year: 2022, era: "大模型", image: "🏗️", url: "https://en.wikipedia.org/wiki/Whisper_(speech_processing_system)", description: "OpenAI 多语种语音识别模型。" },
    { id: "alphazero_2017", label: "AlphaZero", type: "Architecture", year: 2017, era: "强化学习", image: "🏗️", url: "https://en.wikipedia.org/wiki/AlphaZero", description: "从零自学棋类，超越 AlphaGo。" },
    { id: "muzero_2019", label: "MuZero", type: "Architecture", year: 2019, era: "强化学习", image: "🏗️", url: "https://en.wikipedia.org/wiki/MuZero", description: "无需环境模型也能规划的强化学习。" },
    { id: "dqn_2015", label: "DQN", type: "Architecture", year: 2015, era: "强化学习", image: "🏗️", url: "https://en.wikipedia.org/wiki/Deep_reinforcement_learning", description: "深度 Q 网络，Atari 游戏从像素直接学习。" },
    { id: "ppo_2017", label: "PPO", type: "Architecture", year: 2017, era: "强化学习", image: "🏗️", url: "https://en.wikipedia.org/wiki/Proximal_policy_optimization", description: "近端策略优化，RLHF 常用算法。" },
    { id: "t5_2019", label: "T5", type: "Architecture", year: 2019, era: "大模型", image: "🏗️", url: "https://en.wikipedia.org/wiki/T5_(language_model)", description: "『一切皆文本到文本』的统一框架。" },
    { id: "mistral_2023", label: "Mistral", type: "Architecture", year: 2023, era: "大模型", image: "🏗️", url: "https://en.wikipedia.org/wiki/Mistral_AI", description: "高效开放权重模型系列。" },
    { id: "mixtral_2023", label: "Mixtral (MoE)", type: "Architecture", year: 2023, era: "大模型", image: "🏗️", url: "https://en.wikipedia.org/wiki/Mixtral", description: "稀疏混合专家开放模型。" },
    { id: "palm_2022", label: "PaLM", type: "Architecture", year: 2022, era: "大模型", image: "🏗️", url: "https://en.wikipedia.org/wiki/PaLM", description: "Google 5400 亿参数稠密模型。" },
    { id: "chinchilla_2022", label: "Chinchilla", type: "Architecture", year: 2022, era: "大模型", image: "🏗️", url: "https://en.wikipedia.org/wiki/Chinchilla_(language_model)", description: "揭示『模型大小 vs 数据量』最优配比。" },
    { id: "roberta_2019", label: "RoBERTa", type: "Architecture", year: 2019, era: "大模型", image: "🏗️", url: "https://en.wikipedia.org/wiki/RoBERTa", description: "更大语料与动态掩码的 BERT 强化版。" },
    { id: "gpt4o_2024", label: "GPT-4o", type: "Architecture", year: 2024, era: "大模型", image: "🏗️", url: "https://en.wikipedia.org/wiki/GPT-4", description: "原生多模态、低延迟的旗舰模型。" },
    { id: "o1_2024", label: "OpenAI o1", type: "Architecture", year: 2024, era: "大模型", image: "🏗️", url: "https://en.wikipedia.org/wiki/OpenAI_o1", description: "强调推理时『思考』的推理模型。" },
    { id: "deepseek_r1_2025", label: "DeepSeek-R1", type: "Architecture", year: 2025, era: "大模型", image: "🏗️", url: "https://en.wikipedia.org/wiki/DeepSeek", description: "强化学习驱动的开源推理模型。" },
    { id: "ernie_2019", label: "文心一言 (ERNIE)", type: "Architecture", year: 2019, era: "大模型", image: "🏗️", url: "https://en.wikipedia.org/wiki/Ernie_Bot", description: "百度知识增强大模型。" },
    { id: "qwen_2023", label: "通义千问 (Qwen)", type: "Architecture", year: 2023, era: "大模型", image: "🏗️", url: "https://en.wikipedia.org/wiki/Qwen", description: "阿里开源大模型系列。" },
    { id: "glm_2019", label: "GLM / ChatGLM", type: "Architecture", year: 2019, era: "大模型", image: "🏗️", url: "https://en.wikipedia.org/wiki/GLM_(model)", description: "智谱自回归填空统一架构。" },
    { id: "llama2_2023", label: "Llama 2", type: "Architecture", year: 2023, era: "大模型", image: "🏗️", url: "https://en.wikipedia.org/wiki/LLaMA", description: "Meta 开放权重第二版大模型。" },
    { id: "llama3_2024", label: "Llama 3", type: "Architecture", year: 2024, era: "大模型", image: "🏗️", url: "https://en.wikipedia.org/wiki/LLaMA", description: "Meta 更大规模、更强开放权重模型。" },
    { id: "phi_2023", label: "Phi", type: "Architecture", year: 2023, era: "大模型", image: "🏗️", url: "https://en.wikipedia.org/wiki/Phi_(language_model)", description: "微软『小但强』的教科书级小模型系列。" },
    { id: "bloom_2022", label: "BLOOM", type: "Architecture", year: 2022, era: "大模型", image: "🏗️", url: "https://en.wikipedia.org/wiki/BLOOM_(language_model)", description: "开放科学协作的多语言大模型。" },
    { id: "opt_2022", label: "OPT", type: "Architecture", year: 2022, era: "大模型", image: "🏗️", url: "https://en.wikipedia.org/wiki/OPT_(language_model)", description: "Meta 开放预训练Transformer。" },
    { id: "falcon_2022", label: "Falcon", type: "Architecture", year: 2022, era: "大模型", image: "🏗️", url: "https://en.wikipedia.org/wiki/Falcon_(language_model)", description: "阿联酋 TII 训练的开源大模型。" },
    { id: "grok_2023", label: "Grok", type: "Architecture", year: 2023, era: "大模型", image: "🏗️", url: "https://en.wikipedia.org/wiki/Grok_(chatbot)", description: "xAI 大模型，深度集成 X 平台。" },
    { id: "wudao_2021", label: "悟道 (Wu Dao)", type: "Architecture", year: 2021, era: "大模型", image: "🏗️", url: "https://en.wikipedia.org/wiki/WuDao", description: "智源研究院超大规模中文模型。" },
    { id: "pangu_2021", label: "盘古 (Pangu)", type: "Architecture", year: 2021, era: "大模型", image: "🏗️", url: "https://www.huawei.com/", description: "华为全场景大模型。" },
    { id: "baidu_apollo_2013", label: "Apollo (自动驾驶)", type: "Architecture", year: 2013, era: "大模型", image: "🏗️", url: "https://www.apollo.auto/", description: "百度开源自动驾驶平台。" },
    { id: "baidu_paddle_2016", label: "PaddlePaddle", type: "Architecture", year: 2016, era: "深度学习", image: "🏗️", url: "https://www.paddlepaddle.org.cn/", description: "百度开源深度学习框架。" },

    /* =========================== 算法 Algorithm =========================== */
    { id: "adam_2014", label: "Adam 优化器", type: "Algorithm", year: 2014, era: "深度学习", image: "⚙️", url: "https://en.wikipedia.org/wiki/Stochastic_gradient_descent", description: "自适应矩估计的常用优化器。" },
    { id: "dropout_2012", label: "Dropout", type: "Algorithm", year: 2012, era: "深度学习", image: "⚙️", url: "https://en.wikipedia.org/wiki/Dropout_(neural_networks)", description: "训练时随机置零神经元以防过拟合。" },
    { id: "batchnorm_2015", label: "批归一化 (BatchNorm)", type: "Algorithm", year: 2015, era: "深度学习", image: "⚙️", url: "https://en.wikipedia.org/wiki/Batch_normalization", description: "稳定深层网络训练、加速收敛。" },
    { id: "xgboost_2014", label: "XGBoost", type: "Algorithm", year: 2014, era: "统计学习", image: "⚙️", url: "https://en.wikipedia.org/wiki/XGBoost", description: "梯度提升树，表格数据竞赛常胜。" },
    { id: "random_forest_2001", label: "随机森林", type: "Algorithm", year: 2001, era: "统计学习", image: "⚙️", url: "https://en.wikipedia.org/wiki/Random_forest", description: "集成多棵决策树的分类/回归方法。" },
    { id: "lora_2021", label: "LoRA", type: "Algorithm", year: 2021, era: "大模型", image: "⚙️", url: "https://en.wikipedia.org/wiki/Low-rank_adaptation_of_large_language_models", description: "低秩适配，高效微调大模型。" },

    /* =========================== 硬件 Hardware =========================== */
    { id: "a100_2020", label: "NVIDIA A100", type: "Hardware", year: 2020, era: "大模型", image: "🔧", url: "https://www.nvidia.com/en-us/data-center/a100/", description: "Ampere 架构 GPU，大模型训练主力。" },
    { id: "v100_2017", label: "NVIDIA V100", type: "Hardware", year: 2017, era: "深度学习", image: "🔧", url: "https://www.nvidia.com/en-us/data-center/v100/", description: "Volta 架构 GPU，引入张量核心。" },
    { id: "loihi_2017", label: "Loihi (神经形态)", type: "Hardware", year: 2017, era: "深度学习", image: "🔧", url: "https://en.wikipedia.org/wiki/Neuromorphic_engineering", description: "Intel 神经形态芯片，事件驱动计算。" },
    { id: "apple_neural_2017", label: "Apple 神经网络引擎", type: "Hardware", year: 2017, era: "大模型", image: "🔧", url: "https://en.wikipedia.org/wiki/Apple_silicon", description: "端侧 NPU，支撑设备端 AI。" },
    { id: "edge_tpu_2018", label: "Edge TPU", type: "Hardware", year: 2018, era: "大模型", image: "🔧", url: "https://cloud.google.com/edge-tpu", description: "Google 端侧推理加速芯片。" },
    { id: "ipu_2016", label: "Graphcore IPU", type: "Hardware", year: 2016, era: "深度学习", image: "🔧", url: "https://www.graphcore.ai/", description: "面向图计算的智能处理器。" },

    /* ============================= 论文 Paper ============================= */
    { id: "mcculloch_pitts_1943_paper", label: "MP 神经元 (1943)", type: "Paper", year: 1943, era: "奠基", image: "📄", url: "https://doi.org/10.1007/BF02478259", description: "《A Logical Calculus of Ideas Immanent in Nervous Activity》。" },
    { id: "hebb_1949_book", label: "The Organization of Behavior (1949)", type: "Paper", year: 1949, era: "奠基", image: "📄", url: "https://en.wikipedia.org/wiki/The_Organization_of_Behavior", description: "Hebb 提出神经可塑性法则。" },
    { id: "neocognitron_1980_paper", label: "Neocognitron (1980)", type: "Paper", year: 1980, era: "联结主义", image: "📄", url: "https://doi.org/10.1016/0031-3203(80)90051-4", description: " Fukushima 提出分层卷积式网络。" },
    { id: "vae_2013_paper", label: "VAE 论文 (2013)", type: "Paper", year: 2013, era: "深度学习", image: "📄", url: "https://arxiv.org/abs/1312.6114", description: "《Auto-Encoding Variational Bayes》。" },
    { id: "adam_2014_paper", label: "Adam 论文 (2014)", type: "Paper", year: 2014, era: "深度学习", image: "📄", url: "https://arxiv.org/abs/1412.6980", description: "《Adam: A Method for Stochastic Optimization》。" },
    { id: "unet_2015_paper", label: "U-Net 论文 (2015)", type: "Paper", year: 2015, era: "深度学习", image: "📄", url: "https://arxiv.org/abs/1505.04597", description: "生物医学图像分割网络。" },
    { id: "yolo_2015_paper", label: "YOLO 论文 (2015)", type: "Paper", year: 2015, era: "深度学习", image: "📄", url: "https://arxiv.org/abs/1506.02640", description: "《You Only Look Once》。" },
    { id: "googlenet_2014_paper", label: "GoogLeNet 论文 (2014)", type: "Paper", year: 2014, era: "深度学习", image: "📄", url: "https://arxiv.org/abs/1409.4842", description: "《Going Deeper with Convolutions》。" },
    { id: "vit_2020_paper", label: "ViT 论文 (2020)", type: "Paper", year: 2020, era: "大模型", image: "📄", url: "https://arxiv.org/abs/2010.11929", description: "《An Image is Worth 16x16 Words》。" },
    { id: "clip_2021_paper", label: "CLIP 论文 (2021)", type: "Paper", year: 2021, era: "大模型", image: "📄", url: "https://arxiv.org/abs/2103.00020", description: "《Learning Transferable Visual Models》。" },
    { id: "dalle_2021_paper", label: "DALL·E 论文 (2021)", type: "Paper", year: 2021, era: "大模型", image: "📄", url: "https://arxiv.org/abs/2102.12092", description: "《Zero-Shot Text-to-Image Generation》。" },
    { id: "scaling_2020_paper", label: "Scaling Laws (2020)", type: "Paper", year: 2020, era: "大模型", image: "📄", url: "https://arxiv.org/abs/2001.08361", description: "《Scaling Laws for Neural Language Models》。" },
    { id: "cot_2022_paper", label: "Chain-of-Thought (2022)", type: "Paper", year: 2022, era: "大模型", image: "📄", url: "https://arxiv.org/abs/2201.11903", description: "《Chain-of-Thought Prompting Elicits Reasoning》。" },
    { id: "rlhf_2022_paper", label: "InstructGPT (2022)", type: "Paper", year: 2022, era: "大模型", image: "📄", url: "https://arxiv.org/abs/2203.02155", description: "《Training Language Models to Follow Instructions》。" },
    { id: "seq2seq_2014_paper", label: "Seq2Seq (2014)", type: "Paper", year: 2014, era: "深度学习", image: "📄", url: "https://arxiv.org/abs/1409.3215", description: "《Sequence to Sequence Learning with NN》。" },
    { id: "glove_2014_paper", label: "GloVe (2014)", type: "Paper", year: 2014, era: "深度学习", image: "📄", url: "https://nlp.stanford.edu/projects/glove/", description: "全局词向量表示。" },
    { id: "dqn_2015_paper", label: "DQN (Nature 2015)", type: "Paper", year: 2015, era: "强化学习", image: "📄", url: "https://www.nature.com/articles/nature14236", description: "《Human-level control through deep RL》。" },
    { id: "ppo_2017_paper", label: "PPO 论文 (2017)", type: "Paper", year: 2017, era: "强化学习", image: "📄", url: "https://arxiv.org/abs/1707.06347", description: "《Proximal Policy Optimization Algorithms》。" },
    { id: "alphazero_2017_paper", label: "AlphaZero (2017)", type: "Paper", year: 2017, era: "强化学习", image: "📄", url: "https://science.sciencemag.org/content/362/6419/1140", description: "《Mastering Chess and Shogi by Self-Play》。" },
    { id: "muzero_2019_paper", label: "MuZero (2019)", type: "Paper", year: 2019, era: "强化学习", image: "📄", url: "https://www.nature.com/articles/s41586-019-1924-0", description: "《Mastering Atari without a Model》。" },
    { id: "chinchilla_2022_paper", label: "Chinchilla (2022)", type: "Paper", year: 2022, era: "大模型", image: "📄", url: "https://arxiv.org/abs/2203.15556", description: "《Training Compute-Optimal LLMs》。" },
    { id: "palm_2022_paper", label: "PaLM 论文 (2022)", type: "Paper", year: 2022, era: "大模型", image: "📄", url: "https://arxiv.org/abs/2204.02311", description: "《PaLM: Scaling Language Modeling》。" },
    { id: "gpt4_2023_paper", label: "GPT-4 技术报告 (2023)", type: "Paper", year: 2023, era: "大模型", image: "📄", url: "https://arxiv.org/abs/2303.08774", description: "《GPT-4 Technical Report》。" },
    { id: "deepseek_r1_2025_paper", label: "DeepSeek-R1 (2025)", type: "Paper", year: 2025, era: "大模型", image: "📄", url: "https://arxiv.org/abs/2501.12948", description: "《Incentivizing Reasoning in LLMs via RL》。" },
    { id: "llama_2023_paper", label: "LLaMA 论文 (2023)", type: "Paper", year: 2023, era: "大模型", image: "📄", url: "https://arxiv.org/abs/2302.13971", description: "《LLaMA: Open and Efficient Foundation Models》。" },

    /* ============================= 事件 Event ============================= */
    { id: "mp_1943_event", label: "MP 神经元模型 (1943)", type: "Event", year: 1943, era: "奠基", image: "⭐", url: "https://en.wikipedia.org/wiki/Artificial_neuron", description: "首个形式化神经元，神经网络思想起点。" },
    { id: "hebb_1949_event", label: "赫布法则提出 (1949)", type: "Event", year: 1949, era: "奠基", image: "⭐", url: "https://en.wikipedia.org/wiki/Hebbian_theory", description: "可塑性学习法则奠定联结主义基础。" },
    { id: "adaline_1960_event", label: "ADALINE 问世 (1960)", type: "Event", year: 1960, era: "奠基", image: "⭐", url: "https://en.wikipedia.org/wiki/ADALINE", description: "自适应线性元件推动早期神经网络。" },
    { id: "neocognitron_1980_event", label: "Neocognitron (1980)", type: "Event", year: 1980, era: "联结主义", image: "⭐", url: "https://en.wikipedia.org/wiki/Neocognitron", description: "卷积式网络雏形出现。" },
    { id: "boltzmann_1985_event", label: "玻尔兹曼机 (1985)", type: "Event", year: 1985, era: "联结主义", image: "⭐", url: "https://en.wikipedia.org/wiki/Boltzmann_machine", description: "Hinton 等提出能量模型。" },
    { id: "watson_jeopardy_2011", label: "Watson 赢得问答 (2011)", type: "Event", year: 2011, era: "大数据", image: "⭐", url: "https://en.wikipedia.org/wiki/Watson_(computer)", description: "IBM Watson 在 Jeopardy! 击败人类冠军。" },
    { id: "dqn_atari_2015_event", label: "DQN 通关 Atari (2015)", type: "Event", year: 2015, era: "强化学习", image: "⭐", url: "https://en.wikipedia.org/wiki/Deep_reinforcement_learning", description: "深度强化学习从像素直接玩游戏。" },
    { id: "alphazero_2017_event", label: "AlphaZero 自博弈 (2017)", type: "Event", year: 2017, era: "强化学习", image: "⭐", url: "https://en.wikipedia.org/wiki/AlphaZero", description: "无人类数据自学棋类登顶。" },
    { id: "gpt4_2023_event", label: "GPT-4 发布 (2023)", type: "Event", year: 2023, era: "大模型", image: "⭐", url: "https://en.wikipedia.org/wiki/GPT-4", description: "多模态大模型引发广泛震撼。" },
    { id: "llama_2023_event", label: "LLaMA 开源 (2023)", type: "Event", year: 2023, era: "大模型", image: "⭐", url: "https://en.wikipedia.org/wiki/LLaMA", description: "Meta 开放权重点燃开源生态。" },
    { id: "gemini_2023_event", label: "Gemini 发布 (2023)", type: "Event", year: 2023, era: "大模型", image: "⭐", url: "https://en.wikipedia.org/wiki/Gemini_(language_model)", description: "Google 原生多模态大模型。" },
    { id: "claude_2023_event", label: "Claude 发布 (2023)", type: "Event", year: 2023, era: "大模型", image: "⭐", url: "https://en.wikipedia.org/wiki/Claude_(language_model)", description: "Anthropic 对话模型问世。" },
    { id: "midjourney_2022_event", label: "Midjourney 面世 (2022)", type: "Event", year: 2022, era: "大模型", image: "⭐", url: "https://en.wikipedia.org/wiki/Midjourney", description: "文生图艺术化普及。" },
    { id: "sora_2024_event", label: "Sora 发布 (2024)", type: "Event", year: 2024, era: "大模型", image: "⭐", url: "https://en.wikipedia.org/wiki/Sora_(text-to-video_model)", description: "OpenAI 文生视频模型亮相。" },
    { id: "china_ai_plan_2017", label: "中国新一代 AI 规划 (2017)", type: "Event", year: 2017, era: "大模型", image: "⭐", url: "https://www.gov.cn/", description: "国家层面将 AI 列为重点战略。" },
    { id: "eu_ai_act_2024", label: "欧盟 AI 法案 (2024)", type: "Event", year: 2024, era: "大模型", image: "⭐", url: "https://artificialintelligenceact.eu/", description: "全球首部综合性 AI 监管法律。" },
    { id: "altman_ousted_2023", label: "Altman 罢免风波 (2023)", type: "Event", year: 2023, era: "大模型", image: "⭐", url: "https://en.wikipedia.org/wiki/OpenAI", description: "OpenAI CEO 短暂被免后又复职。" },
    { id: "gpt4o_2024_event", label: "GPT-4o 发布 (2024)", type: "Event", year: 2024, era: "大模型", image: "⭐", url: "https://openai.com/index/hello-gpt-4o/", description: "实时多模态语音交互旗舰。" },
    { id: "deepseek_r1_2025_event", label: "DeepSeek-R1 震动 (2025)", type: "Event", year: 2025, era: "大模型", image: "⭐", url: "https://en.wikipedia.org/wiki/DeepSeek", description: "开源推理模型引发算力叙事重估。" },
    { id: "stargate_2025", label: "Stargate 计划 (2025)", type: "Event", year: 2025, era: "大模型", image: "⭐", url: "https://openai.com/index/announcing-the-stargate-project/", description: "OpenAI 与 Oracle 等千亿美元算力计划。" },
    { id: "bletchley_2023", label: "布莱切利 AI 安全峰会 (2023)", type: "Event", year: 2023, era: "大模型", image: "⭐", url: "https://www.gov.uk/", description: "多国签署 AI 风险声明。" },
    { id: "us_eo_2023", label: "美国 AI 行政令 (2023)", type: "Event", year: 2023, era: "大模型", image: "⭐", url: "https://www.whitehouse.gov/", description: "拜登签署 AI 安全与透明行政令。" },
    { id: "tesla_autopilot_2014_event", label: "Tesla Autopilot (2014)", type: "Event", year: 2014, era: "强化学习", image: "⭐", url: "https://en.wikipedia.org/wiki/Tesla_Autopilot", description: "量产车辅助驾驶普及化。" },
    { id: "openai_founded_2015_event", label: "OpenAI 成立 (2015)", type: "Event", year: 2015, era: "大模型", image: "⭐", url: "https://en.wikipedia.org/wiki/OpenAI", description: "非营利实验室宣告成立。" },
    { id: "deepmind_founded_2010_event", label: "DeepMind 成立 (2010)", type: "Event", year: 2010, era: "大模型", image: "⭐", url: "https://en.wikipedia.org/wiki/DeepMind", description: "伦敦 AI 实验室创立。" },
    { id: "imagenet_event_2009", label: "ImageNet 发布 (2009)", type: "Event", year: 2009, era: "大数据", image: "⭐", url: "https://www.image-net.org/", description: "大规模标注数据集开源。" }
  ];

  const NEW_EDGES = [
    /* 奠基：MP 神经元 / 赫布 / ADALINE */
    { source: "mcculloch_1943", target: "mcculloch_pitts_1943_paper", relation: "AUTHOR", year: 1943 },
    { source: "pitts_1943", target: "mcculloch_pitts_1943_paper", relation: "AUTHOR", year: 1943 },
    { source: "mcculloch_pitts_1943_paper", target: "neural_network", relation: "INFLUENCED", year: 1943 },
    { source: "mp_1943_event", target: "mcculloch_1943", relation: "MARKED_BY", year: 1943 },
    { source: "mp_1943_event", target: "neural_network", relation: "INFLUENCED", year: 1943 },
    { source: "hebb_1949", target: "hebbian_learning", relation: "PROPOSED", year: 1949 },
    { source: "hebb_1949", target: "hebb_1949_book", relation: "AUTHOR", year: 1949 },
    { source: "hebb_1949_book", target: "hebbian_learning", relation: "INFLUENCED", year: 1949 },
    { source: "hebb_1949_event", target: "hebb_1949", relation: "MARKED_BY", year: 1949 },
    { source: "hebbian_learning", target: "neural_network", relation: "SUBCLASS_OF", year: 1949 },
    { source: "hebbian_learning", target: "connectionism", relation: "SUBCLASS_OF", year: 1949 },
    { source: "widrow_1960", target: "adaline_1960", relation: "PROPOSED", year: 1960 },
    { source: "adaline_1960", target: "neural_network", relation: "SUBCLASS_OF", year: 1960 },
    { source: "adaline_1960_event", target: "adaline_1960", relation: "MARKED_BY", year: 1960 },
    { source: "werbos_1944", target: "neural_network", relation: "INFLUENCED", year: 1974 },
    { source: "werbos_1944", target: "backprop_1986", relation: "INFLUENCED", year: 1986 },

    /* 联结主义/统计学习先驱 */
    { source: "fukushima_1980", target: "neocognitron_1980", relation: "PROPOSED", year: 1980 },
    { source: "neocognitron_1980", target: "neural_network", relation: "SUBCLASS_OF", year: 1980 },
    { source: "neocognitron_1980", target: "cnn_1998", relation: "BUILT_UPON", year: 1980 },
    { source: "fukushima_1980", target: "neocognitron_1980_paper", relation: "AUTHOR", year: 1980 },
    { source: "neocognitron_1980_paper", target: "neocognitron_1980", relation: "AUTHOR", year: 1980 },
    { source: "neocognitron_1980_event", target: "neocognitron_1980", relation: "MARKED_BY", year: 1980 },
    { source: "sejnowski_1947", target: "boltzmann_1985", relation: "INFLUENCED", year: 1985 },
    { source: "sejnowski_1947", target: "rbm_2006", relation: "INFLUENCED", year: 2006 },
    { source: "sejnowski_1947", target: "deep_learning", relation: "INFLUENCED", year: 2006 },
    { source: "boltzmann_1985_event", target: "boltzmann_1985", relation: "MARKED_BY", year: 1985 },
    { source: "pearl_1936", target: "bayesian_net", relation: "PROPOSED", year: 1985 },
    { source: "bayesian_net", target: "machine_learning", relation: "SUBCLASS_OF", year: 1985 },
    { source: "pearl_1936", target: "causal_inference", relation: "PROPOSED", year: 1990 },
    { source: "causal_inference", target: "machine_learning", relation: "SUBCLASS_OF", year: 1990 },
    { source: "bayesian_net", target: "causal_inference", relation: "BUILT_UPON", year: 1990 },
    { source: "zadeh_1965", target: "fuzzy_logic", relation: "PROPOSED", year: 1965 },
    { source: "fuzzy_logic", target: "machine_learning", relation: "SUBCLASS_OF", year: 1965 },

    /* 强化学习先驱 */
    { source: "sutton_1958", target: "reinforcement_learning", relation: "INFLUENCED", year: 1988 },
    { source: "sutton_1958", target: "q_learning_1989", relation: "INFLUENCED", year: 1988 },
    { source: "sutton_1958", target: "rl_field", relation: "INFLUENCED", year: 1988 },
    { source: "barto_1948", target: "reinforcement_learning", relation: "INFLUENCED", year: 1988 },
    { source: "barto_1948", target: "rl_field", relation: "INFLUENCED", year: 1988 },
    { source: "watkins_1958", target: "q_learning_1989", relation: "AUTHOR", year: 1988 },
    { source: "sutton_1958", target: "barto_1948", relation: "ADVISOR", year: 1988 },

    /* 深度学习技术栈 */
    { source: "hinton_1947", target: "rbm_2006", relation: "INFLUENCED", year: 2006 },
    { source: "rbm_2006", target: "boltzmann_1985", relation: "BUILT_UPON", year: 2006 },
    { source: "rbm_2006", target: "deep_learning", relation: "BUILT_UPON", year: 2006 },
    { source: "autoencoder_1986", target: "neural_network", relation: "SUBCLASS_OF", year: 1986 },
    { source: "autoencoder_1986", target: "deep_learning", relation: "BUILT_UPON", year: 1986 },
    { source: "vae_2013", target: "autoencoder_1986", relation: "BUILT_UPON", year: 2013 },
    { source: "vae_2013", target: "generative_ai", relation: "SUBCLASS_OF", year: 2013 },
    { source: "vae_2013", target: "deep_learning", relation: "SUBCLASS_OF", year: 2013 },
    { source: "vae_2013", target: "vae_2013_paper", relation: "AUTHOR", year: 2013 },
    { source: "vae_2013_paper", target: "vae_2013", relation: "AUTHOR", year: 2013 },
    { source: "adam_2014", target: "deep_learning", relation: "INFLUENCED", year: 2014 },
    { source: "adam_2014", target: "adam_2014_paper", relation: "AUTHOR", year: 2014 },
    { source: "adam_2014_paper", target: "adam_2014", relation: "AUTHOR", year: 2014 },
    { source: "dropout_2012", target: "neural_network", relation: "BUILT_UPON", year: 2012 },
    { source: "dropout_2012", target: "deep_learning", relation: "INFLUENCED", year: 2012 },
    { source: "batchnorm_2015", target: "cnn_1998", relation: "BUILT_UPON", year: 2015 },
    { source: "batchnorm_2015", target: "deep_learning", relation: "INFLUENCED", year: 2015 },
    { source: "unet_2015", target: "image_generation", relation: "BUILT_UPON", year: 2015 },
    { source: "unet_2015", target: "cv", relation: "INFLUENCED", year: 2015 },
    { source: "unet_2015", target: "unet_2015_paper", relation: "AUTHOR", year: 2015 },
    { source: "unet_2015_paper", target: "unet_2015", relation: "AUTHOR", year: 2015 },
    { source: "yolo_2015", target: "object_detection", relation: "BUILT_UPON", year: 2015 },
    { source: "yolo_2015", target: "cnn_1998", relation: "BUILT_UPON", year: 2015 },
    { source: "yolo_2015", target: "cv", relation: "INFLUENCED", year: 2015 },
    { source: "yolo_2015", target: "yolo_2015_paper", relation: "AUTHOR", year: 2015 },
    { source: "yolo_2015_paper", target: "yolo_2015", relation: "AUTHOR", year: 2015 },
    { source: "googlenet_2014", target: "cnn_1998", relation: "BUILT_UPON", year: 2014 },
    { source: "googlenet_2014", target: "cv", relation: "INFLUENCED", year: 2014 },
    { source: "googlenet_2014", target: "googlenet_2014_paper", relation: "AUTHOR", year: 2014 },
    { source: "googlenet_2014_paper", target: "googlenet_2014", relation: "AUTHOR", year: 2014 },
    { source: "mobilenet_2016", target: "cnn_1998", relation: "BUILT_UPON", year: 2016 },
    { source: "mobilenet_2016", target: "edge_ai", relation: "BUILT_UPON", year: 2016 },
    { source: "gnn_2009", target: "graph_learning", relation: "BUILT_UPON", year: 2009 },
    { source: "gnn_2009", target: "neural_network", relation: "SUBCLASS_OF", year: 2009 },
    { source: "graph_learning", target: "machine_learning", relation: "SUBCLASS_OF", year: 2009 },
    { source: "capsule_2017", target: "cnn_1998", relation: "BUILT_UPON", year: 2017 },
    { source: "capsule_2017", target: "neural_network", relation: "SUBCLASS_OF", year: 2017 },
    { source: "vit_2020", target: "transformer_2017", relation: "BUILT_UPON", year: 2020 },
    { source: "vit_2020", target: "cv", relation: "INFLUENCED", year: 2020 },
    { source: "vit_2020", target: "deep_learning", relation: "SUBCLASS_OF", year: 2020 },
    { source: "vit_2020", target: "vit_2020_paper", relation: "AUTHOR", year: 2020 },
    { source: "vit_2020_paper", target: "vit_2020", relation: "AUTHOR", year: 2020 },
    { source: "xgboost_2014", target: "machine_learning", relation: "SUBCLASS_OF", year: 2014 },
    { source: "random_forest_2001", target: "machine_learning", relation: "SUBCLASS_OF", year: 2001 },
    { source: "lora_2021", target: "llm", relation: "BUILT_UPON", year: 2021 },
    { source: "lora_2021", target: "deep_learning", relation: "INFLUENCED", year: 2021 },

    /* 多模态 / 生成式 */
    { source: "clip_2021", target: "multimodal", relation: "BUILT_UPON", year: 2021 },
    { source: "clip_2021", target: "nlp", relation: "BUILT_UPON", year: 2021 },
    { source: "clip_2021", target: "cv", relation: "BUILT_UPON", year: 2021 },
    { source: "clip_2021", target: "openai_2015", relation: "RELEASED", year: 2021 },
    { source: "clip_2021", target: "clip_2021_paper", relation: "AUTHOR", year: 2021 },
    { source: "clip_2021_paper", target: "clip_2021", relation: "AUTHOR", year: 2021 },
    { source: "clip_2021_paper", target: "attention_paper_2017", relation: "CITE", year: 2021 },
    { source: "dalle_2021", target: "clip_2021", relation: "BUILT_UPON", year: 2021 },
    { source: "dalle_2021", target: "generative_ai", relation: "SUBCLASS_OF", year: 2021 },
    { source: "dalle_2021", target: "image_generation", relation: "BUILT_UPON", year: 2021 },
    { source: "dalle_2021", target: "openai_2015", relation: "RELEASED", year: 2021 },
    { source: "dalle_2021", target: "dalle_2021_paper", relation: "AUTHOR", year: 2021 },
    { source: "dalle_2021_paper", target: "dalle_2021", relation: "AUTHOR", year: 2021 },
    { source: "image_generation", target: "diffusion_2020", relation: "BUILT_UPON", year: 2020 },
    { source: "image_generation", target: "gans_2014", relation: "BUILT_UPON", year: 2014 },
    { source: "image_generation", target: "cv", relation: "SUBCLASS_OF", year: 2014 },
    { source: "whisper_2022", target: "speech", relation: "BUILT_UPON", year: 2022 },
    { source: "whisper_2022", target: "tts", relation: "INFLUENCED", year: 2022 },
    { source: "whisper_2022", target: "openai_2015", relation: "RELEASED", year: 2022 },
    { source: "midjourney_2022", target: "image_generation", relation: "INFLUENCED", year: 2022 },
    { source: "midjourney_2022", target: "generative_ai", relation: "INFLUENCED", year: 2022 },
    { source: "midjourney_2022_event", target: "midjourney_2022", relation: "MARKED_BY", year: 2022 },
    { source: "stability_2020", target: "stable_diffusion_2022", relation: "RELEASED", year: 2022 },
    { source: "stability_2020", target: "generative_ai", relation: "INFLUENCED", year: 2022 },
    { source: "huggingface_2016", target: "llm", relation: "INFLUENCED", year: 2016 },
    { source: "huggingface_2016", target: "generative_ai", relation: "INFLUENCED", year: 2016 },
    { source: "bloom_2022", target: "huggingface_2016", relation: "RELEASED", year: 2022 },
    { source: "bloom_2022", target: "llm", relation: "SUBCLASS_OF", year: 2022 },
    { source: "bloom_2022", target: "nlp", relation: "INFLUENCED", year: 2022 },

    /* 强化学习里程碑 */
    { source: "dqn_2015", target: "reinforcement_learning", relation: "SUBCLASS_OF", year: 2015 },
    { source: "dqn_2015", target: "deep_learning", relation: "BUILT_UPON", year: 2015 },
    { source: "dqn_2015", target: "deepmind_2010", relation: "RELEASED", year: 2015 },
    { source: "dqn_2015", target: "dqn_2015_paper", relation: "AUTHOR", year: 2015 },
    { source: "dqn_2015_paper", target: "dqn_2015", relation: "AUTHOR", year: 2015 },
    { source: "dqn_atari_2015_event", target: "dqn_2015", relation: "MARKED_BY", year: 2015 },
    { source: "dqn_atari_2015_event", target: "deepmind_2010", relation: "MARKED_BY", year: 2015 },
    { source: "ppo_2017", target: "reinforcement_learning", relation: "SUBCLASS_OF", year: 2017 },
    { source: "ppo_2017", target: "openai_2015", relation: "RELEASED", year: 2017 },
    { source: "ppo_2017", target: "rlhf", relation: "BUILT_UPON", year: 2017 },
    { source: "ppo_2017", target: "ppo_2017_paper", relation: "AUTHOR", year: 2017 },
    { source: "ppo_2017_paper", target: "ppo_2017", relation: "AUTHOR", year: 2017 },
    { source: "alphazero_2017", target: "alphago_2016", relation: "BUILT_UPON", year: 2017 },
    { source: "alphazero_2017", target: "reinforcement_learning", relation: "SUBCLASS_OF", year: 2017 },
    { source: "alphazero_2017", target: "deepmind_2010", relation: "RELEASED", year: 2017 },
    { source: "alphazero_2017", target: "alphazero_2017_paper", relation: "AUTHOR", year: 2017 },
    { source: "alphazero_2017_paper", target: "alphazero_2017", relation: "AUTHOR", year: 2017 },
    { source: "alphazero_2017_event", target: "alphazero_2017", relation: "MARKED_BY", year: 2017 },
    { source: "muzero_2019", target: "alphazero_2017", relation: "BUILT_UPON", year: 2019 },
    { source: "muzero_2019", target: "reinforcement_learning", relation: "SUBCLASS_OF", year: 2019 },
    { source: "muzero_2019", target: "deepmind_2010", relation: "RELEASED", year: 2019 },
    { source: "muzero_2019", target: "muzero_2019_paper", relation: "AUTHOR", year: 2019 },
    { source: "muzero_2019_paper", target: "muzero_2019", relation: "AUTHOR", year: 2019 },
    { source: "world_model", target: "reinforcement_learning", relation: "SUBCLASS_OF", year: 2018 },
    { source: "world_model", target: "robotics", relation: "BUILT_UPON", year: 2018 },

    /* 大模型族谱 */
    { source: "t5_2019", target: "transformer_2017", relation: "BUILT_UPON", year: 2019 },
    { source: "t5_2019", target: "nlp", relation: "INFLUENCED", year: 2019 },
    { source: "t5_2019", target: "google_1998", relation: "RELEASED", year: 2019 },
    { source: "roberta_2019", target: "bert_2018", relation: "BUILT_UPON", year: 2019 },
    { source: "roberta_2019", target: "nlp", relation: "INFLUENCED", year: 2019 },
    { source: "roberta_2019", target: "meta_2004", relation: "RELEASED", year: 2019 },
    { source: "mistral_2023", target: "llm", relation: "SUBCLASS_OF", year: 2023 },
    { source: "mistral_2023", target: "moe", relation: "BUILT_UPON", year: 2023 },
    { source: "mistral_2023", target: "generative_ai", relation: "INFLUENCED", year: 2023 },
    { source: "mixtral_2023", target: "mistral_2023", relation: "BUILT_UPON", year: 2023 },
    { source: "mixtral_2023", target: "moe", relation: "SUBCLASS_OF", year: 2023 },
    { source: "mixtral_2023", target: "llm", relation: "SUBCLASS_OF", year: 2023 },
    { source: "palm_2022", target: "llm", relation: "SUBCLASS_OF", year: 2022 },
    { source: "palm_2022", target: "google_1998", relation: "RELEASED", year: 2022 },
    { source: "palm_2022", target: "scaling_law", relation: "BUILT_UPON", year: 2022 },
    { source: "palm_2022", target: "palm_2022_paper", relation: "AUTHOR", year: 2022 },
    { source: "palm_2022_paper", target: "palm_2022", relation: "AUTHOR", year: 2022 },
    { source: "chinchilla_2022", target: "scaling_law", relation: "BUILT_UPON", year: 2022 },
    { source: "chinchilla_2022", target: "deepmind_2010", relation: "RELEASED", year: 2022 },
    { source: "chinchilla_2022", target: "llm", relation: "INFLUENCED", year: 2022 },
    { source: "chinchilla_2022", target: "chinchilla_2022_paper", relation: "AUTHOR", year: 2022 },
    { source: "chinchilla_2022_paper", target: "chinchilla_2022", relation: "AUTHOR", year: 2022 },
    { source: "gpt4o_2024", target: "gpt4_2023", relation: "BUILT_UPON", year: 2024 },
    { source: "gpt4o_2024", target: "multimodal", relation: "BUILT_UPON", year: 2024 },
    { source: "gpt4o_2024", target: "openai_2015", relation: "RELEASED", year: 2024 },
    { source: "gpt4o_2024_event", target: "gpt4o_2024", relation: "MARKED_BY", year: 2024 },
    { source: "o1_2024", target: "llm", relation: "SUBCLASS_OF", year: 2024 },
    { source: "o1_2024", target: "rlhf", relation: "BUILT_UPON", year: 2024 },
    { source: "o1_2024", target: "openai_2015", relation: "RELEASED", year: 2024 },
    { source: "phi_2023", target: "llm", relation: "SUBCLASS_OF", year: 2023 },
    { source: "phi_2023", target: "microsoft_1975", relation: "RELEASED", year: 2023 },
    { source: "opt_2022", target: "llm", relation: "SUBCLASS_OF", year: 2022 },
    { source: "opt_2022", target: "meta_2004", relation: "RELEASED", year: 2022 },
    { source: "falcon_2022", target: "llm", relation: "SUBCLASS_OF", year: 2022 },
    { source: "falcon_2022", target: "generative_ai", relation: "INFLUENCED", year: 2022 },
    { source: "grok_2023", target: "llm", relation: "SUBCLASS_OF", year: 2023 },
    { source: "grok_2023", target: "xai_2023", relation: "RELEASED", year: 2023 },
    { source: "grok_2023", target: "transformer_2017", relation: "BUILT_UPON", year: 2023 },
    { source: "xai_2023", target: "grok_2023", relation: "RELEASED", year: 2023 },
    { source: "xai_2023", target: "llm", relation: "INFLUENCED", year: 2023 },
    { source: "wudao_2021", target: "llm", relation: "SUBCLASS_OF", year: 2021 },
    { source: "wudao_2021", target: "baai_2018", relation: "RELEASED", year: 2021 },
    { source: "wudao_2021", target: "foundation_model", relation: "BUILT_UPON", year: 2021 },
    { source: "baai_2018", target: "wudao_2021", relation: "RELEASED", year: 2021 },
    { source: "baai_2018", target: "foundation_model", relation: "INFLUENCED", year: 2018 },
    { source: "foundation_model", target: "deep_learning", relation: "SUBCLASS_OF", year: 2021 },
    { source: "foundation_model", target: "llm", relation: "BUILT_UPON", year: 2021 },
    { source: "pangu_2021", target: "llm", relation: "SUBCLASS_OF", year: 2021 },
    { source: "pangu_2021", target: "huawei_1987", relation: "RELEASED", year: 2021 },

    /* 中国 AI 与开源生态 */
    { source: "baidu_2000", target: "ernie_2019", relation: "RELEASED", year: 2019 },
    { source: "baidu_2000", target: "baidu_paddle_2016", relation: "RELEASED", year: 2016 },
    { source: "baidu_2000", target: "baidu_apollo_2013", relation: "RELEASED", year: 2013 },
    { source: "baidu_2000", target: "deep_learning", relation: "INFLUENCED", year: 2013 },
    { source: "baidu_2000", target: "llm", relation: "INFLUENCED", year: 2019 },
    { source: "ernie_2019", target: "llm", relation: "SUBCLASS_OF", year: 2019 },
    { source: "ernie_2019", target: "transformer_2017", relation: "BUILT_UPON", year: 2019 },
    { source: "baidu_apollo_2013", target: "robotics", relation: "BUILT_UPON", year: 2013 },
    { source: "baidu_apollo_2013", target: "cv", relation: "INFLUENCED", year: 2013 },
    { source: "baidu_apollo_2013", target: "reinforcement_learning", relation: "BUILT_UPON", year: 2013 },
    { source: "tencent_ai_2016", target: "generative_ai", relation: "INFLUENCED", year: 2016 },
    { source: "tencent_ai_2016", target: "cv", relation: "INFLUENCED", year: 2016 },
    { source: "tencent_ai_2016", target: "llm", relation: "INFLUENCED", year: 2016 },
    { source: "alibaba_damo_2017", target: "qwen_2023", relation: "RELEASED", year: 2023 },
    { source: "alibaba_damo_2017", target: "llm", relation: "INFLUENCED", year: 2017 },
    { source: "qwen_2023", target: "llm", relation: "SUBCLASS_OF", year: 2023 },
    { source: "qwen_2023", target: "transformer_2017", relation: "BUILT_UPON", year: 2023 },
    { source: "huawei_1987", target: "pangu_2021", relation: "RELEASED", year: 2021 },
    { source: "huawei_1987", target: "llm", relation: "INFLUENCED", year: 2021 },
    { source: "bytedance_2012", target: "generative_ai", relation: "INFLUENCED", year: 2012 },
    { source: "bytedance_2012", target: "llm", relation: "INFLUENCED", year: 2012 },
    { source: "sense_time_2014", target: "cv", relation: "INFLUENCED", year: 2014 },
    { source: "megvii_2011", target: "cv", relation: "INFLUENCED", year: 2011 },
    { source: "iflytek_1999", target: "speech", relation: "INFLUENCED", year: 1999 },
    { source: "iflytek_1999", target: "tts", relation: "INFLUENCED", year: 1999 },
    { source: "zhipu_2019", target: "glm_2019", relation: "RELEASED", year: 2019 },
    { source: "zhipu_2019", target: "llm", relation: "INFLUENCED", year: 2019 },
    { source: "glm_2019", target: "llm", relation: "SUBCLASS_OF", year: 2019 },
    { source: "glm_2019", target: "transformer_2017", relation: "BUILT_UPON", year: 2019 },
    { source: "moonshot_2023", target: "llm", relation: "INFLUENCED", year: 2023 },
    { source: "minimax_2021", target: "llm", relation: "INFLUENCED", year: 2021 },
    { source: "minimax_2021", target: "generative_ai", relation: "INFLUENCED", year: 2021 },
    { source: "zero_one_2023", target: "llm", relation: "INFLUENCED", year: 2023 },
    { source: "zero_one_2023", target: "lee_kaifu_1956", relation: "AFFILIATED_WITH", role: "founder", year: 2023 },
    { source: "lee_kaifu_1956", target: "microsoft_1975", relation: "AFFILIATED_WITH", role: "ex_exec", year: 2000 },
    { source: "lee_kaifu_1956", target: "google_1998", relation: "AFFILIATED_WITH", role: "ex_china_head", year: 2005 },
    { source: "lee_kaifu_1956", target: "zero_one_2023", relation: "AFFILIATED_WITH", role: "founder", year: 2023 },
    { source: "lee_kaifu_1956", target: "llm", relation: "INFLUENCED", year: 2023 },
    { source: "shum_1966", target: "microsoft_1975", relation: "AFFILIATED_WITH", role: "exec", year: 1998 },
    { source: "shum_1966", target: "cv", relation: "INFLUENCED", year: 1998 },
    { source: "yang_qiang_1969", target: "machine_learning", relation: "INFLUENCED", year: 1998 },
    { source: "yang_qiang_1969", target: "llm", relation: "INFLUENCED", year: 2023 },
    { source: "zhou_zhihua_1973", target: "machine_learning", relation: "INFLUENCED", year: 2000 },
    { source: "zhang_yaqin_1963", target: "microsoft_1975", relation: "AFFILIATED_WITH", role: "exec", year: 1998 },
    { source: "zhang_yaqin_1963", target: "baidu_2000", relation: "AFFILIATED_WITH", role: "ex_president", year: 2014 },
    { source: "zhang_yaqin_1963", target: "deep_learning", relation: "INFLUENCED", year: 2014 },
    { source: "fan_jim_1990", target: "nvidia_1993", relation: "AFFILIATED_WITH", role: "researcher", year: 2018 },
    { source: "fan_jim_1990", target: "embodied_ai", relation: "INFLUENCED", year: 2021 },
    { source: "fan_jim_1990", target: "robotics", relation: "INFLUENCED", year: 2021 },
    { source: "embodied_ai", target: "ai_agents", relation: "SUBCLASS_OF", year: 2021 },
    { source: "embodied_ai", target: "robotics", relation: "BUILT_UPON", year: 2021 },

    /* 人物与机构/方向 */
    { source: "kurzweil_1948", target: "agi", relation: "INFLUENCED", year: 2005 },
    { source: "kurzweil_1948", target: "nlp", relation: "INFLUENCED", year: 1990 },
    { source: "brooks_1954", target: "robotics", relation: "INFLUENCED", year: 1990 },
    { source: "brooks_1954", target: "mit_1861", relation: "AFFILIATED_WITH", role: "professor", year: 1986 },
    { source: "thrun_1967", target: "robotics", relation: "INFLUENCED", year: 2005 },
    { source: "thrun_1967", target: "stanford_1885", relation: "AFFILIATED_WITH", role: "professor", year: 2003 },
    { source: "thrun_1967", target: "google_1998", relation: "AFFILIATED_WITH", role: "researcher", year: 2007 },
    { source: "thrun_1967", target: "deep_learning", relation: "INFLUENCED", year: 2015 },
    { source: "ng_1976", target: "machine_learning", relation: "INFLUENCED", year: 2000 },
    { source: "ng_1976", target: "stanford_1885", relation: "AFFILIATED_WITH", role: "professor", year: 2008 },
    { source: "ng_1976", target: "google_brain", relation: "AFFILIATED_WITH", role: "cofounder", year: 2011 },
    { source: "ng_1976", target: "deep_learning", relation: "INFLUENCED", year: 2010 },
    { source: "ng_1976", target: "baidu_2000", relation: "AFFILIATED_WITH", role: "ex_ai_head", year: 2014 },
    { source: "karpathy_1986", target: "nlp", relation: "INFLUENCED", year: 2015 },
    { source: "karpathy_1986", target: "openai_2015", relation: "AFFILIATED_WITH", role: "researcher", year: 2017 },
    { source: "karpathy_1986", target: "llm", relation: "INFLUENCED", year: 2020 },
    { source: "shazeer_1976", target: "transformer_2017", relation: "AUTHOR", year: 2017 },
    { source: "shazeer_1976", target: "google_1998", relation: "AFFILIATED_WITH", role: "researcher", year: 2017 },
    { source: "shazeer_1976", target: "llm", relation: "INFLUENCED", year: 2018 },
    { source: "devlin_1979", target: "bert_2018", relation: "AUTHOR", year: 2018 },
    { source: "devlin_1979", target: "google_1998", relation: "AFFILIATED_WITH", role: "researcher", year: 2018 },
    { source: "radford_1986", target: "gpt1_2018", relation: "AUTHOR", year: 2018 },
    { source: "radford_1986", target: "openai_2015", relation: "AFFILIATED_WITH", role: "researcher", year: 2016 },
    { source: "radford_1986", target: "clip_2021", relation: "AUTHOR", year: 2021 },
    { source: "leike_1986", target: "ai_safety", relation: "INFLUENCED", year: 2020 },
    { source: "leike_1986", target: "openai_2015", relation: "AFFILIATED_WITH", role: "researcher", year: 2017 },
    { source: "leike_1986", target: "anthropic_2021", relation: "AFFILIATED_WITH", role: "researcher", year: 2023 },
    { source: "leike_1986", target: "rlhf", relation: "INFLUENCED", year: 2022 },
    { source: "russell_1962", target: "ai_safety", relation: "PROPOSED", year: 2015 },
    { source: "russell_1962", target: "norvig_1956", relation: "ADVISOR", year: 1995 },
    { source: "russell_1962", target: "agi", relation: "INFLUENCED", year: 2015 },
    { source: "norvig_1956", target: "ai_safety", relation: "INFLUENCED", year: 2015 },
    { source: "norvig_1956", target: "google_1998", relation: "AFFILIATED_WITH", role: "research_director", year: 2000 },
    { source: "norvig_1956", target: "machine_learning", relation: "INFLUENCED", year: 2000 },
    { source: "marcus_1969", target: "nlp", relation: "INFLUENCED", year: 2010 },
    { source: "marcus_1969", target: "neural_network", relation: "INFLUENCED", year: 2010 },
    { source: "crawford_1971", target: "ai_safety", relation: "INFLUENCED", year: 2015 },
    { source: "gebru_1983", target: "ai_safety", relation: "INFLUENCED", year: 2018 },
    { source: "gebru_1983", target: "google_1998", relation: "AFFILIATED_WITH", role: "researcher", year: 2018 },
    { source: "buolamwini_1989", target: "ai_safety", relation: "INFLUENCED", year: 2016 },
    { source: "buolamwini_1989", target: "mit_1861", relation: "AFFILIATED_WITH", role: "researcher", year: 2016 },
    { source: "abbeel_1980", target: "reinforcement_learning", relation: "INFLUENCED", year: 2010 },
    { source: "abbeel_1980", target: "robotics", relation: "INFLUENCED", year: 2010 },
    { source: "levine_1983", target: "robotics", relation: "INFLUENCED", year: 2015 },
    { source: "levine_1983", target: "reinforcement_learning", relation: "INFLUENCED", year: 2015 },
    { source: "levine_1983", target: "deep_learning", relation: "INFLUENCED", year: 2015 },
    { source: "finn_1987", target: "reinforcement_learning", relation: "INFLUENCED", year: 2017 },
    { source: "finn_1987", target: "robotics", relation: "INFLUENCED", year: 2017 },
    { source: "jordan_1956", target: "machine_learning", relation: "INFLUENCED", year: 1995 },
    { source: "jordan_1956", target: "deep_learning", relation: "INFLUENCED", year: 2010 },
    { source: "mitchell_1951", target: "machine_learning", relation: "INFLUENCED", year: 1997 },
    { source: "mitchell_1951", target: "cmu_1900", relation: "AFFILIATED_WITH", role: "professor", year: 1997 },
    { source: "domingos_1965", target: "machine_learning", relation: "INFLUENCED", year: 2000 },
    { source: "girshick_1982", target: "cv", relation: "INFLUENCED", year: 2014 },
    { source: "girshick_1982", target: "object_detection", relation: "INFLUENCED", year: 2014 },
    { source: "girshick_1982", target: "meta_2004", relation: "AFFILIATED_WITH", role: "researcher", year: 2015 },

    /* 概念层级 */
    { source: "transfer_learning", target: "machine_learning", relation: "SUBCLASS_OF", year: 1995 },
    { source: "transfer_learning", target: "deep_learning", relation: "BUILT_UPON", year: 2010 },
    { source: "few_shot", target: "machine_learning", relation: "SUBCLASS_OF", year: 2019 },
    { source: "few_shot", target: "llm", relation: "BUILT_UPON", year: 2019 },
    { source: "self_supervised", target: "machine_learning", relation: "SUBCLASS_OF", year: 2018 },
    { source: "self_supervised", target: "deep_learning", relation: "BUILT_UPON", year: 2018 },
    { source: "multimodal", target: "machine_learning", relation: "SUBCLASS_OF", year: 2018 },
    { source: "multimodal", target: "nlp", relation: "BUILT_UPON", year: 2018 },
    { source: "multimodal", target: "cv", relation: "BUILT_UPON", year: 2018 },
    { source: "moe", target: "deep_learning", relation: "SUBCLASS_OF", year: 2017 },
    { source: "moe", target: "llm", relation: "BUILT_UPON", year: 2017 },
    { source: "rlhf", target: "reinforcement_learning", relation: "SUBCLASS_OF", year: 2022 },
    { source: "rlhf", target: "llm", relation: "BUILT_UPON", year: 2022 },
    { source: "rlhf", target: "ai_safety", relation: "BUILT_UPON", year: 2022 },
    { source: "rlhf", target: "rlhf_2022_paper", relation: "AUTHOR", year: 2022 },
    { source: "rlhf_2022_paper", target: "rlhf", relation: "AUTHOR", year: 2022 },
    { source: "rlhf_2022_paper", target: "gpt3_2020", relation: "CITE", year: 2022 },
    { source: "cot", target: "nlp", relation: "SUBCLASS_OF", year: 2022 },
    { source: "cot", target: "llm", relation: "BUILT_UPON", year: 2022 },
    { source: "cot", target: "cot_2022_paper", relation: "AUTHOR", year: 2022 },
    { source: "cot_2022_paper", target: "cot", relation: "AUTHOR", year: 2022 },
    { source: "emergent", target: "llm", relation: "SUBCLASS_OF", year: 2022 },
    { source: "emergent", target: "scaling_law", relation: "BUILT_UPON", year: 2022 },
    { source: "knowledge_graph", target: "nlp", relation: "SUBCLASS_OF", year: 2012 },
    { source: "knowledge_graph", target: "machine_learning", relation: "BUILT_UPON", year: 2012 },
    { source: "machine_translation", target: "nlp", relation: "SUBCLASS_OF", year: 1954 },
    { source: "machine_translation", target: "transformer_2017", relation: "BUILT_UPON", year: 2017 },
    { source: "machine_translation", target: "seq2seq_2014_paper", relation: "INFLUENCED", year: 2014 },
    { source: "seq2seq_2014_paper", target: "sutskever_1986", relation: "AUTHOR", year: 2014 },
    { source: "seq2seq_2014_paper", target: "nlp", relation: "INFLUENCED", year: 2014 },
    { source: "glove_2014_paper", target: "word2vec_2013", relation: "CITE", year: 2014 },
    { source: "glove_2014_paper", target: "nlp", relation: "INFLUENCED", year: 2014 },
    { source: "object_detection", target: "cv", relation: "SUBCLASS_OF", year: 2001 },
    { source: "tts", target: "speech", relation: "SUBCLASS_OF", year: 1980 },
    { source: "tts", target: "deep_learning", relation: "BUILT_UPON", year: 2010 },
    { source: "qa", target: "nlp", relation: "SUBCLASS_OF", year: 1961 },
    { source: "qa", target: "llm", relation: "BUILT_UPON", year: 2020 },
    { source: "recommendation", target: "machine_learning", relation: "SUBCLASS_OF", year: 1990 },
    { source: "recommendation", target: "deep_learning", relation: "BUILT_UPON", year: 2010 },
    { source: "neural_arch_search", target: "deep_learning", relation: "SUBCLASS_OF", year: 2017 },
    { source: "edge_ai", target: "deep_learning", relation: "SUBCLASS_OF", year: 2018 },
    { source: "edge_ai", target: "edge_tpu_2018", relation: "BUILT_UPON", year: 2018 },
    { source: "edge_ai", target: "apple_neural_2017", relation: "BUILT_UPON", year: 2017 },

    /* 硬件 */
    { source: "a100_2020", target: "nvidia_1993", relation: "RELEASED", year: 2020 },
    { source: "a100_2020", target: "llm", relation: "INFLUENCED", year: 2020 },
    { source: "a100_2020", target: "deep_learning", relation: "INFLUENCED", year: 2020 },
    { source: "v100_2017", target: "nvidia_1993", relation: "RELEASED", year: 2017 },
    { source: "v100_2017", target: "deep_learning", relation: "INFLUENCED", year: 2017 },
    { source: "nvidia_1993", target: "a100_2020", relation: "RELEASED", year: 2020 },
    { source: "nvidia_1993", target: "v100_2017", relation: "RELEASED", year: 2017 },
    { source: "cerebras_2016", target: "deep_learning", relation: "INFLUENCED", year: 2016 },
    { source: "cerebras_2016", target: "llm", relation: "INFLUENCED", year: 2020 },
    { source: "loihi_2017", target: "neural_network", relation: "INFLUENCED", year: 2017 },
    { source: "apple_neural_2017", target: "edge_ai", relation: "BUILT_UPON", year: 2017 },
    { source: "edge_tpu_2018", target: "google_1998", relation: "RELEASED", year: 2018 },
    { source: "edge_tpu_2018", target: "edge_ai", relation: "BUILT_UPON", year: 2018 },
    { source: "ipu_2016", target: "graphcore_2016", relation: "RELEASED", year: 2016 },
    { source: "ipu_2016", target: "deep_learning", relation: "INFLUENCED", year: 2016 },

    /* 事件：里程碑与监管 */
    { source: "watson_jeopardy_2011", target: "ibm_1911", relation: "RELEASED", year: 2011 },
    { source: "watson_jeopardy_2011", target: "nlp", relation: "INFLUENCED", year: 2011 },
    { source: "gpt4_2023_event", target: "gpt4_2023", relation: "MARKED_BY", year: 2023 },
    { source: "llama_2023_event", target: "llama_2023", relation: "MARKED_BY", year: 2023 },
    { source: "gemini_2023_event", target: "gemini_2023", relation: "MARKED_BY", year: 2023 },
    { source: "claude_2023_event", target: "claude_2023", relation: "MARKED_BY", year: 2023 },
    { source: "sora_2024_event", target: "sora_2024", relation: "MARKED_BY", year: 2024 },
    { source: "china_ai_plan_2017", target: "llm", relation: "INFLUENCED", year: 2017 },
    { source: "china_ai_plan_2017", target: "deep_learning", relation: "INFLUENCED", year: 2017 },
    { source: "eu_ai_act_2024", target: "ai_safety", relation: "INFLUENCED", year: 2024 },
    { source: "altman_ousted_2023", target: "altman_1985", relation: "MARKED_BY", year: 2023 },
    { source: "altman_ousted_2023", target: "openai_2015", relation: "MARKED_BY", year: 2023 },
    { source: "deepseek_r1_2025_event", target: "deepseek_r1_2025", relation: "MARKED_BY", year: 2025 },
    { source: "deepseek_r1_2025_event", target: "deepseek_2023", relation: "MARKED_BY", year: 2025 },
    { source: "deepseek_r1_2025", target: "deepseek_2023", relation: "BUILT_UPON", year: 2025 },
    { source: "deepseek_r1_2025", target: "llm", relation: "SUBCLASS_OF", year: 2025 },
    { source: "deepseek_r1_2025", target: "rlhf", relation: "BUILT_UPON", year: 2025 },
    { source: "deepseek_r1_2025", target: "deepseek_r1_2025_paper", relation: "AUTHOR", year: 2025 },
    { source: "deepseek_r1_2025_paper", target: "deepseek_r1_2025", relation: "AUTHOR", year: 2025 },
    { source: "stargate_2025", target: "openai_2015", relation: "MARKED_BY", year: 2025 },
    { source: "stargate_2025", target: "microsoft_1975", relation: "PARTNERED_WITH", year: 2025 },
    { source: "bletchley_2023", target: "ai_safety", relation: "INFLUENCED", year: 2023 },
    { source: "us_eo_2023", target: "ai_safety", relation: "INFLUENCED", year: 2023 },
    { source: "tesla_autopilot_2014_event", target: "robotics", relation: "INFLUENCED", year: 2014 },
    { source: "openai_founded_2015_event", target: "openai_2015", relation: "MARKED_BY", year: 2015 },
    { source: "openai_founded_2015_event", target: "altman_1985", relation: "MARKED_BY", year: 2015 },
    { source: "deepmind_founded_2010_event", target: "deepmind_2010", relation: "MARKED_BY", year: 2010 },
    { source: "deepmind_founded_2010_event", target: "hassabis_1976", relation: "MARKED_BY", year: 2010 },
    { source: "imagenet_event_2009", target: "imagenet_paper_2009", relation: "MARKED_BY", year: 2009 },
    { source: "imagenet_event_2009", target: "fei_fei_li_1976", relation: "MARKED_BY", year: 2009 },
    { source: "scaling_2020_paper", target: "scaling_law", relation: "AUTHOR", year: 2020 },
    { source: "scaling_law", target: "llm", relation: "INFLUENCED", year: 2020 },
    { source: "gpt4_2023_paper", target: "gpt4_2023", relation: "AUTHOR", year: 2023 },
    { source: "gpt4_2023_paper", target: "openai_2015", relation: "AUTHOR", year: 2023 },
    { source: "llama_2023_paper", target: "llama_2023", relation: "AUTHOR", year: 2023 },
    { source: "llama_2023_paper", target: "meta_2004", relation: "AUTHOR", year: 2023 },
    { source: "llama2_2023", target: "llama_2023", relation: "BUILT_UPON", year: 2023 },
    { source: "llama2_2023", target: "llm", relation: "SUBCLASS_OF", year: 2023 },
    { source: "llama2_2023", target: "meta_2004", relation: "RELEASED", year: 2023 },
    { source: "llama3_2024", target: "llama2_2023", relation: "BUILT_UPON", year: 2024 },
    { source: "llama3_2024", target: "llm", relation: "SUBCLASS_OF", year: 2024 },
    { source: "llama3_2024", target: "meta_2004", relation: "RELEASED", year: 2024 }
  ];

  const AI_DATA_300 = {
    nodes: BASE.nodes.concat(NEW_NODES),
    edges: BASE.edges.concat(NEW_EDGES)
  };
  if (typeof window !== "undefined") window.AI_DATA_300 = AI_DATA_300;
  if (typeof module !== "undefined" && module.exports) module.exports = AI_DATA_300;
})();
